
language: python
cache: pip
install:
- pip install mkdocs
- pip install mkdocs-material
script:
- mkdocs build
deploy:
  provider: pages
  edge: true
  cleanup: false
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: site/
  on:
    branch: master
